apiVersion: apps/v1
kind: Deployment
metadata:
  name: piminer
  labels:
    app: piminer
env:
- name: WALLET_ID
  value: "4B4RSqqyoMQBNSnfTkWPFVTMVHzBGoY5WRn7BobfY1Myid5p6HaszDs7nyGVVNHGRTMh6HmFwxZMYR5Hc83frXULS1UfChC"
- name: WORKER_NAME
  value: "piminer"
spec:
  selector:
    matchLabels:
      app: piminer
  template:
    metadata:
      labels:
        app: piminer
    spec:
      containers:
      - name: piminer
        image: 192.168.1.16:32000/piminer-v.01:registry
        ports:
        - containerPort: 80