apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8miner
  labels:
    app: k8miner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8miner
  template:
    metadata:
      labels:
        app: k8miner
    spec:
      containers:
        - name: k8miner
          image: 192.168.1.45:32000/k8miner:registry
          ports:
            - containerPort: 80
          securityContext:
            privileged: true

