apiVersion: apps/v1
kind: Deployment
metadata:
  name: pimine
  labels:
    app: pimine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pimine
  template:
    metadata:
      labels:
        app: pimine
    spec:
      containers:
      - name: pimine
        image: http://192.168.1.16:32000/piminer-v.01  # Use the image you built locally
        imagePullPolicy: IfNotPresent
        env:
        - name: WALLET_ID
          value: "4B4RSqqyoMQBNSnfTkWPFVTMVHzBGoY5WRn7BobfY1Myid5p6HaszDs7nyGVVNHGRTMh6HmFwxZMYR5Hc83frXULS1UfChC"
        - name: WORKER_NAME
          value: "pimine"
        command: ["/bin/bash", "-c"]
        args: [ "/app/xmrig/build/xmrig-o gulf.moneroocean.stream:10128 -u $WALLET_ID -p $WORKER_NAME"]
        resources:
          limits:
            cpu: "1"
            memory: "50Mi"
          requests:
            cpu: "50m"
            memory: "50Mi"
        ports:
        - containerPort: 10128
